triggers:

  - name: trigger-dv-man
    type: trigger
    source:
      message: 'tesetinwglthtbth12 triifgfuggujythree in yml oekke13ewuh52122'
      counter: 2

  - name: triggertest2
    type: trigger
    source:
      message: 'tesetinwglthtbth12 triifgfuggujythree in yml oekke13ewuh52322'
      counter: 2