jobs:
  - name: dv-ci
    type: manifest
    steps:
      - IN: dv-repo
      - IN: r1
      - IN: job2-trigger
      - TASK: managed
      - OUT: dv-img
      - OUT: dv-test-ecs
      - OUT: box-test-triton
      - OUT: dv-img-opts
    flags:
      - dv
  - name: dv-man
    type: manifest
    steps:
      - IN: dv-img
      - IN: r1
      - IN: job2-trigger
      - TASK: managed
      - IN: trigger-test-deploy-dv
      #- IN: dv-img-opts
      - OUT: dv-test-ecs
      - OUT: dv-params
      - OUT: env-test-ecs
  - name: dv-test-ecs
    type: manifest
    steps:
      - IN: dv-man
      - IN: r1
      - IN: dv-ci
      - TASK: managed
      - IN: env-test-ecs
      - IN: trigger-test-deploy-dv
      - IN: dv-params
      - OUT: r2
    flags:
      - dv

  - name: box-ci
    type: runSh
    steps:
      - TASK:
        - script: sudo apt-get install tree
        - script: tree
        - script: tree -F IN

  - name: box-man
    type: manifest
    steps:
      - IN: box-img
      - IN: r1
      - IN: job1-trigger
      - TASK: managed
      - IN: box-img-opts
      - OUT: box-test-triton
      - OUT: box-test-aws-ecs

  - name: box-test-triton
    type: manifest
    steps:
      - IN: box-man
      - IN: r1
      - IN: dv-ci
      - TASK: managed
      - IN: trigger-test-deploy-box
      - IN: box-t-tpc-params
      #- IN: box-t-params
      - IN: env-test-triton
  - name: box-test-aws-ecs
    type: manifest
    steps:
      - IN: box-man
      - IN: r1
      - IN: job1-trigger
      - TASK: managed
      - IN: trigger-test-deploy-box
      - IN: box-t-params
      - IN: box-t-ecs-params
      #- IN: env-test-ecs
  # - name: dv-test2
  #   type: manifest
  #   steps:
  #     - IN: dv-ci
  #     - IN: r2
  #     - TASK: managed
