triggers:
   - name: triggerTest
     type: trigger
     source:
       counter: 1

   - name: trigger
     type: prodTrigger
     source:
       counter: 1

   - name: triggerTest
     type: betaTrigger
     source:
       counter: 1