jobs:
  - name: runSh
    type: runSh
    steps:
      - IN:
        - gitRepo
      - OUT:
        - image
      - TASK:
        - script: sudo apt-get install -y jq
    on_success:
      - script: echo 'successful runSh'
    on_failure:
      - script: echo 'failed runSh'

  - name: release
    type: release
    steps:
      - IN:
        - gitRepo
        - dockerOptions
        - integration
      - OUT:
        - image
      - TASK:
        - script: sudo apt-get install -y jq
    on_success:
      - script: echo 'successful release'
    on_failure:
      - script: echo 'failed release'

  - name: deploy
    type: deploy
    steps:
      - IN:
        - gitRepo
        - params
        - cluster
      - OUT:
        - image
      - TASK:
        - script: sudo apt-get install -y jq
    on_success:
      - script: echo 'successful deploy'
    on_failure:
      - script: echo 'failed deploy'

  - name: manifest
    type: manifest
    steps:
      - IN:
        - gitRepo
        - replicas
        - version
      - OUT:
        - image
      - TASK:
        - script: sudo apt-get install -y jq
    on_success:
      - script: echo 'successful manifest'
    on_failure:
      - script: echo 'failed manifest'