jobs:
  - name: runSh
    type: runSh
    steps:
      - TASK:
        - script: sudo apt-get install -y jq
    on_success:
      - script: echo 'successful runSh'
    on_failure:
      - script: echo 'failed runSh'

  - name: release
    type: release
    steps:
      - TASK:
        - script: sudo apt-get install -y jq
    on_success:
      - script: echo 'successful release'
    on_failure:
      - script: echo 'failed release'

  - name: deploy
    type: deploy
    steps:
      - TASK:
        - script: sudo apt-get install -y jq
    on_success:
      - script: echo 'successful deploy'
    on_failure:
      - script: echo 'failed deploy'

  - name: manifest
    type: manifest
    steps:
      - TASK:
        - script: sudo apt-get install -y jq
    on_success:
      - script: echo 'successful manifest'
    on_failure:
      - script: echo 'failed manifest'