jobs:
  - name: managed
    type: managed
    steps:
    on_success:
      - script: echo 'successful managed'
    on_failure:
      - script: echo 'failed managed'

  - name: runSh
    type: runSh
    steps:
      - TASK:
        - script: sudo apt-get install -y jq
    on_success:
      - script: echo 'successful runSh'
    on_failure:
      - script: echo 'failed runSh'

  - name: runCI
    type: runCI
    steps:
      - TASK:
        - script: sudo apt-get install -y jq
    on_success:
      - script: echo 'successful runCI'
    on_failure:
      - script: echo 'failed runCI'
  - name: release
    type: release
    steps:
      - TASK:
        - script: sudo apt-get install -y jq
    on_success:
      - script: echo 'successful release'
    on_failure:
      - script: echo 'failed release'

  - name: rSyncSteps
    type: rSyncSteps
    steps:
      - TASK:
        - script: sudo apt-get install -y jq
    on_success:
      - script: echo 'successful rSyncSteps'
    on_failure:
      - script: echo 'failed rSyncSteps'

  - name: deploy
    type: deploy
    steps:
      - TASK:
        - script: sudo apt-get install -y jq
    on_success:
      - script: echo 'successful deploy'
    on_failure:
      - script: echo 'failed deploy'

  - name: manifest
    type: manifest
    steps:
      - TASK:
        - script: sudo apt-get install -y jq
    on_success:
      - script: echo 'successful manifest'
    on_failure:
      - script: echo 'failed manifest'