jobs:
  - name: dv-ci
    type: manifest
    steps:
      - IN: dv-repo
      - TASK: managed
      - OUT: dv-img
      - OUT: dv-test-ecs
      - OUT: box-test-triton
  - name: box-ci
    type: manifest
    steps:
      - IN: box-repo
      - TASK: managed
      - OUT: box-img

  - name: dv-man
    type: manifest
    steps:
      - IN: dv-img
      - TASK: managed
      - IN: trigger-test-deploy-dv
      - IN: dv-img-opts
      - OUT: dv-test-ecs
  - name: box-man
    type: manifest
    steps:
      - IN: box-img
      - TASK: managed
      - IN: box-img-opts
      - OUT: box-test-triton
      - OUT: box-test-aws-ecs

  - name: box-test-triton
    type: manifest
    steps:
      - IN: box-man
      - IN: dv-ci
      - TASK: managed
      - IN: trigger-test-deploy-box
      - IN: box-t-tpc-params
      - IN: box-t-params
      - IN: env-test-triton
  - name: box-test-aws-ecs
    type: manifest
    steps:
      - IN: box-man
      - TASK: managed
      - IN: trigger-test-deploy-box
      - IN: box-t-params
      - IN: box-t-ecs-params
      - IN: env-test-ecs
  - name: dv-test-ecs
    type: manifest
    steps:
      - IN: dv-man
      - IN: dv-ci
      - TASK: managed
      - IN: env-test-ecs
      - IN: trigger-test-deploy-dv
      - IN: dv-params