jobs:
  - name: test-job
    type: manifest
    steps:
      - GET: image1-test
      - GET: image2-test
      - GET: image3-test
      - GET: triggertest2

  - name: pipe-man
    type: manifest
    steps:
      - GET: pipe1-image
      - GET: pipe1-opts
      - GET: pipe1-params
        applyTo:
          - pipe1-image
      - GET: trigger-dv-man

  - name: test-job1
    type: manifest
    steps:
      - GET: test-job
      - GET: pipe1-image

  - name: test-job2
    type: manifest
    steps:
      - GET: test-job1
      - GET: image4-test
      - PUT: test1

  - name: pipe-test
    type: ecsDeploy
    steps:
      - GET: pipe-man
      - GET: env-test