jobs:
  - name: runSh
    type: runSh
    steps:
        - IN: gitRepo
        - TASK:
            - script: sudo apt-get install -y jq
        
        
  - name: runSh-60-sec
    type: runSh
    steps:
        - IN: gitRepo
        - TASK:
            - script: sudo apt-get update
            - script: sleep 60s
            
  - name: fast-runsh-job
    type: runSh
    steps:
        - IN: rel-alpha
        - OUT: unsed-res-1
        - TASK:
            - script: echo "running job"
            
  - name: rel-alpha
    type: release
    steps:
        - IN: image
        - IN: alpha-ver
        - TASK: managed
          bump: alpha

  - name: manifest
    type: manifest
    steps:
        - IN: gitRepo
        - OUT: image
        - TASK: managed

  - name: runSh2
    type: runSh
    steps:
        - IN: manifest
        - IN: gitRepo
        - TASK:
            - script: echo "running job"

  - name: runSh3
    type: runSh
    steps:
        - IN: runSh2
        - IN: gitRepo
        - TASK:
           - script: echo "running job"

  - name: runSh4
    type: runSh
    steps:
        - IN: runSh3
        - IN: manifest
        - IN: gitRepo        
        - TASK:
           - script: echo "running job"

        
