jobs:
  - name: dv-ci
    type: manifest
    steps:
      - TASK: managed
      - GET: dv-repo
      - PUT: dv-img
  - name: box-ci
    type: manifest
    steps:
      - TASK: managed
      - GET: box-repo
      - PUT: box-img

  - name: dv-man
    type: manifest
    steps:
      - TASK: managed
      - GET: dv-img
      - GET: trigger-test-deploy-dv
      - GET: dv-img-opts
      - PUT: dv-test-ecs
  - name: box-man
    type: manifest
    steps:
      - TASK: managed
      - GET: box-img
      - GET: box-img-opts
      - PUT: box-test-triton
      - PUT: box-test-aws-ecs

  - name: box-test-triton
    type: manifest
    steps:
      - TASK: managed
      - GET: box-man
      - GET: trigger-test-deploy-box
      - GET: box-t-tpc-params
      - GET: box-t-params
      - GET: env-test-triton
  - name: box-test-aws-ecs
    type: manifest
    steps:
      - TASK: managed
      - GET: box-man
      - GET: trigger-test-deploy-box
      - GET: box-t-params
      - GET: box-t-ecs-params
      - GET: env-test-ecs
  - name: dv-test-ecs
    type: manifest
    steps:
      - TASK: managed
      - GET: dv-man
      - GET: env-test-ecs
      - GET: trigger-test-deploy-dv
      - GET: dv-params