jobs:
  - name: runSh-d1
    type: runSh
    steps:
        - IN: gitRepo-d1
        - IN: manifest-d1
        - TASK:
            - script: sudo apt-get install -y jq
    on_success:
        - script: echo 'successful runSh'
        - NOTIFY: notification-d1
    on_failure:
        - script: echo 'failed runSh'
        - NOTIFY: notification-d1
  - name: runSh2-d1
    type: runSh
    steps:
        - IN: gitRepo-d1
        - IN: manifest-d1
        - TASK:
            - script: sudo apt-get update
            - script: sleep 60s
    on_success:
        - script: echo 'successful runSh'
        - NOTIFY: notification-d1
    on_failure:
        - script: echo 'failed runSh'
        - NOTIFY: notification-d1

  - name: runSh3-d1
    type: runSh
    steps:
        - IN: runSh2-d1
        - OUT: unsed-res-1-d1
        - TASK:
            - script: sudo apt-get update
            - script: sleep 5m
    on_success:
        - script: echo 'successful runSh'
        - NOTIFY: notification-d1
    on_failure:
        - script: echo 'failed runSh'
        - NOTIFY: notification-d1

  - name: release-d1
    type: release
    steps:
        #- IN: gitRepo1-d1
        - IN: dockerOptions-d1
        - IN: params-d1
        - IN: integration-d1
        - TASK:
            - script: sudo apt-get install -y jq
    on_success:
        - script: echo 'successful release'
        - NOTIFY: notification-d1
    on_failure:
        - script: echo 'failed release'
        - NOTIFY: notification-d1


  - name: manifest-d1
    type: manifest
    steps:
        - IN: gitRepo-d1
        #- IN: replicas-d1
        #- IN: version-d1
        - OUT: image-d1
        - TASK: managed
    on_success:
        - script: echo 'successful manifest'
        #- NOTIFY: notification-d1
    on_failure:
        - script: echo 'failed manifest'
        #- NOTIFY: notification-d1
