jobs:   
  - name: release
    type: release
    steps:
        #- IN: gitRepo
        - IN: dockerOptions
        - IN: params
        - IN: integration
        - TASK:
            - script: sudo apt-get install -y jq
    on_success:
        - script: echo 'successful release'
        - NOTIFY: notification
    on_failure:
        - script: echo 'failed release'
        - NOTIFY: notification

 
