jobs:
  - name: runSh
    type: runSh
    steps:
        - IN: gitRepo
        - IN: manifest
        - TASK:
            - script: sudo apt-get install -y jq
    on_success:
        - script: echo 'successful runSh'
        - NOTIFY: notification
    on_failure:
        - script: echo 'failed runSh'
        - NOTIFY: notification
  - name: runSh2
    type: runSh
    steps:
        - IN: gitRepo
        - IN: manifest
        - TASK:
            - script: sudo apt-get update
            - script: sleep 60s
    on_success:
        - script: echo 'successful runSh'
        - NOTIFY: notification
    on_failure:
        - script: echo 'failed runSh'
        - NOTIFY: notification

  - name: runSh3 
    type: runSh
    steps:
        - IN: runSh2
        - IN: rel-alpha
        - OUT: unsed-res-1
        - TASK:
            - script: sudo apt-get update
    on_success:
        - script: echo 'successful runSh'
        - NOTIFY: notification
    on_failure:
        - script: echo 'failed runSh'
        - NOTIFY: notification

  - name: rel-alpha
    type: release
    steps:
        - IN: image
        - IN: alpha-ver
        - TASK: managed
          bump: alpha
    on_success:
        - script: echo 'successful release'
        - NOTIFY: notification
    on_failure:
        - script: echo 'failed release'
        - NOTIFY: notification

  - name: manifest
    type: manifest
    steps:
        - IN: gitRepo
        - OUT: image
        - TASK: managed
    on_success:
        - script: echo 'successful manifest'
    on_failure:
        - script: echo 'failed manifest'

  - name: manifest2
    type: manifest
    steps:
        - IN: manifest
        - TASK: managed

  - name: manifest3
    type: manifest
    steps:
        - IN: manifest2
        - TASK: managed

  - name: manifest4
    type: manifest
    steps:
        - IN: manifest3
        - TASK: managed
        
