jobs:
  - name: manifest
    type: manifest
    steps:
        - IN: gitRepo
        - TASK: managed
    on_success:
        - script: echo 'successful manifest'
    on_failure:
        - script: echo 'failed manifest'
